management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://studplatform-database.ctzczhzrzupg.eu-west-2.rds.amazonaws.com/testDB
    username: postgres
    password: password256
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0

logging:
  file:
    name: "log"
  config: "classpath:logback-spring.xml"